{{- if .Values.ingress.enabled }}
apiVersion: {{ template "plone.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "plone.fullname" . }}
  labels: {{- include "plone.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "plone.tplValue" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if (and (not (eq .Values.ingress.hostname ".xip.io")) .Values.ingress.hostname .Values.ploneSite) }}
    nginx.ingress.kubernetes.io/rewrite-target: /VirtualHostBase/http/{{ .Values.ingress.hostname }}:80/{{ .Values.ploneSite }}/VirtualHostRoot/$1
    {{- end }}
spec:
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        {{- if .Values.ploneSite }}
        {{- if (and (not (eq .Values.ingress.hostname ".xip.io")) .Values.ploneSite) }}
          - path: /(.*)$
        {{- else }}
          - path: /
        {{- end }}
            backend:
              serviceName: {{ template "plone.fullname" . }}
              servicePort: http
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
              serviceName: {{ template "plone.fullname" . }}
              servicePort: http
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- toYaml .Values.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
