{{- if and .Values.ingress.enabled .Values.ingress.hostname .Values.ploneSite }}
apiVersion: {{ template "plone.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ template "plone.fullname" . }}-zmi
  labels: {{- include "plone.labels" . | nindent 4 }}-zmi
  annotations:
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "plone.tplValue" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/rewrite-target: /VirtualHostBase/http/manage.{{ .Values.ingress.hostname }}:80/VirtualHostRoot/$1
spec:
  rules:
    {{- if .Values.ingress.hostname }}
    - host: manage.{{ .Values.ingress.hostname }}
      http:
        paths:
          - path: /(.*)$
            backend:
              serviceName: {{ template "plone.fullname" . }}
              servicePort: http
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
          - path: {{ default "/" .path }}
            backend:
              serviceName: {{ template "plone.fullname" . }}-zmi
              servicePort: http
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - manage.{{ .Values.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- toYaml .Values.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
