apiVersion: {{ template "plone.deployment.apiVersion" . }}
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  name: {{ template "plone.fullname" . }}
  labels: {{- include "plone.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      io.kompose.service: plone
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: plone
    spec:
      containers:
        - env:
            - name: CORS_ALLOW_METHODS
              value: GET
            - name: CORS_ALLOW_ORIGIN
              value: '*'
            - name: TZ
              value: Europe/Berlin
          image: robbuh/plonews:5.2.2-python37-0.1
          name: plone
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          resources: {}
      restartPolicy: Always
status: {}
