apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file v5.2.2.yml convert -c
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: plone
  name: plone
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: plone
status:
  loadBalancer: {}
