apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -c
    kompose.version: 1.22.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: plone
  name: plone
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: plone
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -c
        kompose.version: 1.22.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: plone
    spec:
      containers:
        - env:
            - name: CORS_ALLOW_METHODS
              value: GET
            - name: CORS_ALLOW_ORIGIN
              value: '*'
            - name: TZ
              value: Europe/Berlin
          image: robbuh/plonews:5.2.2-python37-0.1
          name: plone
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
